### ISSUE TITLE
Add env endpoint 

### ISSUE THREAD

**Issue by rsyvarth** [rsyvarth/tsu#1]
- [x] Add new GET /_/env endpoint
- [x] Return a dict containing all of the environment variables that our lambda can see (should be able to get details from the python docs)
- [x] Deploy it!

**Comment by em-shea** [comment]
Complete: src/api/env_var. 
Currently deployed here: https://vbn42fgi74.execute-api.us-east-1.amazonaws.com/dev/api/env_var
